{
 "title": "Sales Dashboard",
 "time": { "from": "2003-01-06T02:00:00.000Z", "to": "2003-12-09T02:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "year", "label": "Select Year", "query": "2003,2004,2005" }
  ]
 },
 "panels": [
  {
   "title": "Total Orders",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ordernumber) FROM sales_data WHERE year_id = $year  LIMIT 50 "
    }
   ]
  },
  {
   "title": "Orders by Date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ordernumber) as \"Orders: \", orderdate FROM sales_data WHERE year_id = $year GROUP BY orderdate LIMIT 50 "
    }
   ]
  },
  {
   "title": "Order Status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT status, COUNT(ordernumber) as \"Orders: \"\r\nFROM sales_data\r\nWHERE year_id = $year\r\nGROUP BY status\r\nORDER BY\r\n  CASE\r\n    WHEN status = 'Shipped' THEN 1\r\n    WHEN status = 'In Process' THEN 2\r\n    WHEN status = 'Resolved' THEN 3\r\n    WHEN status = 'Disputed' THEN 4\r\n    WHEN status = 'On Hold' THEN 5\r\n    WHEN status = 'Cancelled' THEN 6\r\n    ELSE 999\r\n  END;"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(sales) as \"Total Revenue\" FROM sales_data WHERE year_id = $year LIMIT 50 "
    }
   ]
  },
  {
   "title": "Revenue by Product Line",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(sales), productline FROM sales_data WHERE year_id = $year GROUP BY productline ORDER BY SUM(sales) DESC"
    }
   ]
  },
  {
   "title": "Revenue by Region",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT country as \"Country: \", SUM(sales) as \"Revenue: \" FROM sales_data GROUP BY country LIMIT 50 "
    }
   ]
  }
 ]
}